### ISSUE TITLE
A minor type in the book (chapter 9)

### ISSUE THREAD

**Issue by mnishiguchi** [sasa1977/elixir-in-action#10]
There is a typo in the code for handling `:DOWN` after Listing 9.2.

```elixir
  def handle_info({:DOWN, _, :process, pid, _}, process_registry) do
    {:noreply, deregister_pid(new_registry, pid)} #<- new_registry should be process_registry here
  end
```
The code in this repo is correct:
https://github.com/sasa1977/elixir-in-action/blob/master/code_samples/ch09/pool_supervision/lib/todo/process_registry.ex#L55

Thank you very much for writing such a great book!

**Comment by sasa1977** [comment]
Thanks for reporting. This is already listed in [the book errata](https://manning-content.s3.amazonaws.com/download/2/bc9b4e2-d489-424f-afe5-6206861729ee/juric_exlixirinaction_err_7.html), but it's always better to have a duplicate report than no report at all ;)

Glad you like the book :-)
