### ISSUE TITLE
unnecessary plus one for :erlang.phash()

### ISSUE THREAD

**Issue by nhooyr** [sasa1977/elixir-in-action#12]
https://github.com/sasa1977/elixir-in-action/blob/c6c0813b1e463fe1211a0a5d998b3528752bb7b4/code_samples/ch09/proper_registry_supervision/lib/todo/database.ex#L21

:erlang.phash() already puts the number between 1..n, no need to add one.

**Comment by sasa1977** [comment]
The function used in the code is `:erlang.phash2` (notice the trailing `2` in the name), which returns the result in the range of `0..(n-1)` (see [here](http://erlang.org/doc/man/erlang.html#phash2-2)), so `+1` is needed in this case.

Thanks for submitting the issue anyway :-)

**Comment by nhooyr** [comment]
Oh, why not use `:erlang.phash` then?

**Comment by sasa1977** [comment]
The docs for `phash2` states the following: 

> This BIF is always to be used for hashing terms. It distributes small integers better than phash/2, and it is faster for bignums and binaries.
