### ISSUE TITLE
Ch - 10 Page 284 Erlang Reference Link has changed

### ISSUE THREAD

**Issue by krafttoast** [sasa1977/elixir-in-action#27]
The Book's Reference is: "https://erlang.org/doc/man/ets.html"

The new Link to the ETS Reference in the Erlang Manual is: "https://www.erlang.org/doc/apps/stdlib/ets"

**Comment by mariusbutuc** [comment]
> The Book's Reference is: "https://erlang.org/doc/man/ets.html"

Nice catch! It might not present an obstacle for the reader at this point though, as this link does redirect cleanly (`301 Moved Permanently`) to the new URL.

**Comment by krafttoast** [comment]
Ah yes, funnily enough when I opened the Ticket the Redirect wasn't in place. Maybe the change was recently. Since it's a nonissue now I will close the Ticket :)
