### ISSUE TITLE
Bump Elixir version numbers in `mix.exs`

### ISSUE THREAD

**Issue by sotojuan** [sasa1977/elixir-in-action#7]
I've been going through the book today and used this repo quite a lot. One thing that is annoying is that when you run `iex -S mix` I get an error because the mix files say `elixir: "~> 1.0.0"`.

I can take care of this in a PR if you want :-)

**Comment by sasa1977** [comment]
That should be taken care of in [this branch](https://github.com/sasa1977/elixir-in-action/tree/post-release-updates). Could you take a look, and if there are still issues, let me know?

**Comment by sotojuan** [comment]
Never got around to saying that branch is fine and working!
